- name: Create Calico resources - Tigera Operator
  command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.5/manifests/tigera-operator.yaml
  
- name: Create custom calico resources file
  template:
    src: calico-custom-resource-yaml.j2
    dest: calico-custom-resource.yaml

- name: Create Calico resources - Custom resources
  command: kubectl create -f calico-custom-resource.yaml

- name: Delete Calico custom resources file
  file:
    path: ~/calico-custom-resource.yaml
    state: absent
