- name: Create Cumulus namespace
  command: "kubectl create namespace cumulus"
  become: true
  become_user: "{{ ansible_user }}"

- name: Create Cumulus namespace
  command: "kubectl create namespace cumulus-core"
  become: true
  become_user: "{{ ansible_user }}"

- name: Create Cumulus monitoring namespace
  command: "kubectl create namespace cumulus-monitoring"
  become: true
  become_user: "{{ ansible_user }}"
