- name: Create labadm namespace
  command: "kubectl create namespace lab"
  become: true
  become_user: "{{ ansible_user }}"

- name: Create labadm core namespace
  command: "kubectl create namespace lab-core"
  become: true
  become_user: "{{ ansible_user }}"

- name: Create lab monitoring namespace
  command: "kubectl create namespace lab-monitoring"
  become: true
  become_user: "{{ ansible_user }}"
