ansible_user: user
ansible_become_pass: passwd
ansible_ssh_private_key_file: full/path/to/public/key

architecture: amd64
k8s_version: 1.21.5-00

ports:
  - 80    # http
  - 443   # https
  - 9090  # cockpit
  - 3000  # homepage
  - 61208 # glances
