- name: Wait for all control-plane pods become created
  command: "kubectl get pods --namespace=kube-system --selector tier=control-plane --output=jsonpath='{.items[*].metadata.labels.component}'"
  register: control_plane_pods_created
  until: item in control_plane_pods_created.stdout
  retries: 10
  delay: 30
  with_items:
    - etcd
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
  become: true
  become_user: "{{ ansible_user }}"

- name: Wait until all kube-system control-plane pods are running
  command: kubectl wait --namespace=kube-system --for=condition=Ready pods --selector tier=control-plane --timeout=600s
  register: control_plane_pods_ready
  become: true
  become_user: "{{ ansible_user }}"
