- name: Add Kubernetes GPG keys
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
 
- name: Add Kubernetes repository into sources list
  apt_repository:
    filename: kubernetes.list
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present

- name: Install Kubernetes
  apt:
    name:
    - kubelet={{ k8s_version }}
    - kubeadm={{ k8s_version }}
    - kubectl={{ k8s_version }}
    state: present
    update-cache: yes

- name: Prevent Kubernetes packages from being upgraded
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
