- name: Disable swap
  command: swapoff -a

- name: Install K8s
  include_tasks: k8s.yml
  when: kubernetes_distribution == "k8s" or kubernetes_distribution != "k3s" 

- name: Install K3s
  include_tasks: k3s.yml
  when: kubernetes_distribution == "k3s"
