apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    run: {{ .Values.appName }}
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    name: http
  selector:
    run: {{ .Values.appName }}
