- name: Create Cumulus user
  user:
   name: cumulus
   password: '!' # This is to disable the password
   state: present
   home: /home/cumulus
   shell: /bin/bash

- name: Make sure that the .ssh folder exists
  file:
    path: /home/cumulus/.ssh
    state: directory
  become: true
  become_user: cumulus

- name: Copy cumulus public key pair to the server
  copy:
    src: "{{ ssh_public_key_file }}"
    dest: /home/cumulus/.ssh/authorized_keys
    owner: cumulus
    group: cumulus
    mode: '0600'

- name: Copy data folder to cumulus user home
  copy:
    src: "{{ playbook_dir }}/../data"
    dest: /home/cumulus
    owner: cumulus
    group: cumulus
    mode: '0644'

- name: Copy apps folder to cumulus user home
  copy:
    src: "{{ playbook_dir }}/../apps"
    dest: /home/cumulus
    owner: cumulus
    group: cumulus
    mode: '0644'
