- name: Update & Upgrade packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Install dependencies
  apt:
    name:
      - ufw
      - vim
      - nano
      - curl
      - ca-certificates
      - apt-transport-https
      - gnupg
      - lsb-release
      - software-properties-common
      - python
      - python3
      - python3-pip
    state: present
    update-cache: yes

- name: Allow SSH ports
  ufw:
    rule: allow
    name: "{{ item }}"
  with_items: 
    - OpenSSH
    - ssh

- name: Alow tcp ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items: 
    - 80
    - 443

- name: Enable the firewall
  ufw:
    state: enabled
