#!/bin/bash

# Update packages
sudo apt-get update && sudo apt-get -y upgrade

# Install dependencies
sudo apt-get install -y build-essential software-properties-common zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libbz2-dev gnupg2 curl wget make python python3 python3-pip pythono3-venv

# Add the PPA repository to the sources.list file
echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu bionic main" >> /etc/apt/sources.list

# Add the Ansible GPG key to your system
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367

# Install Ansible
sudo apt-get update && sudo apt-get install -y ansible=2.13.5
