- name: Install dependencies
  apt:
    name:
      - curl
      - ca-certificates
      - apt-transport-https
      - gnupg
      - lsb-release
      - software-properties-common
    state: present
    update-cache: yes

- name: Add Docker GPG keys
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Add Docker repository into sources list
  apt_repository:
    filename: docker
    repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present
    update-cache: yes

- name: Start Docker service
  service:
    name: docker
    state: started
