- name: Add Docker GPG keys
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Add Docker repository into sources list
  apt_repository:
    filename: docker
    repo: "deb [arch={{ architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present
    update-cache: yes
    install_recommends: no

- name: Start Docker service
  service:
    name: docker
    state: started

- name: Ensure Docker group exists
  group:
    name: docker
    state: present
    gid: 1750

- name: Give Docker rights to user
  user:
    name: "{{ std_username }}"
    groups: docker
    append: yes

- name: Ensure permissions for the docker.sock are set
  file:
    path: /var/run/docker.sock
    owner: root
    group: docker
    mode: '0644'

- name: Reboot machine so permissions are set
  reboot:
    reboot_timeout: 300
